import {
  Project,
  ArtifactNode,
  ArtifactEdge,
  RiskItem,
  DecisionItem,
  MilestoneItem,
  TaskItem,
  VersionHistoryItem,
  ActionCenterItem,
  LRDFullDocument,
} from './types';

export const SAMPLE_LRD_FULL_DOCUMENTS: Record<string, LRDFullDocument> = {
  'LRD-2024-001': {
    id: 'LRD-2024-001',
    urn: 'urn:regulus:lrd:LRD-2024-001',
    title: 'EU Directive 2024/1799 (Empowering Consumers for the Green Transition - ECGT)',
    regulation: 'EU Directive 2024/1799 (ECGT)',
    jurisdiction: ['EU', 'DE', 'FR', 'IT', 'ES', 'IE', 'NL', 'PL', 'AT', 'BE'],
    enforcement_date: '2026-09-27',
    grace_period_end: '2027-03-27',
    lrd_owner: {
      id: 'USR-001',
      name: 'Elena Rostova',
      email: 'elena.rostova@ebay.com',
      role: 'Legal Counsel',
    },
    pm_owner: {
      id: 'USR-002',
      name: 'Marcus Vance',
      email: 'marcus.vance@ebay.com',
      role: 'Lead PM',
    },
    status: 'Approved',
    version: '1.0.0',
    created: '2026-01-15T09:00:00Z',
    last_updated: '2026-02-10T14:30:00Z',
    sections: {
      legal_context:
        'EU Directive 2024/1799 amends Directives 2005/29/EC (Unfair Commercial Practices Directive) and 2011/83/EU (Consumer Rights Directive) to empower consumers for the green transition. It establishes strict rules against generic greenwashing, climate-neutral claims based on offsetting, and misleading sustainability labels while introducing mandatory disclosures for durability and repairability.',
      obligations: [
        {
          id: 'OBL-LRD-2024-001-001',
          urn: 'urn:regulus:obligation:OBL-LRD-2024-001-001',
          article: 'Article 3(1)(a)',
          text: "Prohibition of making generic environmental claims ('eco-friendly', 'green', 'climate positive', 'environmentally sound') unless based on recognized official eco-labels or clear verification.",
          type: 'Prohibition',
          affected_surface: ['Search SRP', 'View Item', 'Item Specifics'],
          notes: 'Applies to listing titles, descriptions, and custom item attributes on EU sites.',
          traceability_refs: ['brd-201', 'prd-301', 'jira-501'],
        },
        {
          id: 'OBL-LRD-2024-001-002',
          urn: 'urn:regulus:obligation:OBL-LRD-2024-001-002',
          article: 'Article 3(1)(b)',
          text: 'Prohibition of claims that a product has a neutral, reduced, or positive impact on the environment based on greenhouse gas emissions offsetting.',
          type: 'Prohibition',
          affected_surface: ['View Item', 'Checkout'],
          notes: 'Product-level carbon offset claims strictly prohibited regardless of offset quality.',
          traceability_refs: ['brd-201'],
        },
        {
          id: 'OBL-LRD-2024-001-003',
          urn: 'urn:regulus:obligation:OBL-LRD-2024-001-003',
          article: 'Article 4(2)',
          text: 'Mandatory display of Harmonised Label and Harmonised Notice regarding commercial guarantees of durability provided by producers without extra cost for more than 2 years.',
          type: 'Display',
          affected_surface: ['View Item', 'Listing Flow'],
          notes: 'Harmonised EU badge visual token + text mandatory.',
          traceability_refs: ['prd-301'],
        },
        {
          id: 'OBL-LRD-2024-001-004',
          urn: 'urn:regulus:obligation:OBL-LRD-2024-001-004',
          article: 'Article 4(3)',
          text: 'Mandatory disclosure of Repairability Index score (1.0 to 10.0 scale) or availability of spare parts for energy-related products.',
          type: 'Disclosure',
          affected_surface: ['View Item', 'Search Filter Panel'],
          notes: 'Applies to smartphones, laptops, TVs, washing machines, and appliances.',
          traceability_refs: ['sub-401', 'jira-501'],
        },
        {
          id: 'OBL-LRD-2024-001-005',
          urn: 'urn:regulus:obligation:OBL-LRD-2024-001-005',
          article: 'Article 6(1)',
          text: 'Mandatory disclosure of minimum period during which software updates will be made available for products with digital elements.',
          type: 'Disclosure',
          affected_surface: ['View Item', 'Item Specifics'],
          notes: 'Required for smart home devices, wearables, and computing hardware.',
          traceability_refs: ['sub-401'],
        },
      ],
      ebay_applicability:
        'Applies to all C2C and B2C listings on EU eBay sites (DE, FR, IT, ES, IE, NL, PL, AT) displaying environmental claims, eco-labels, durability claims, or selling electronics and appliances.',
      affected_categories: [
        'Consumer Electronics',
        'Home Appliances',
        'Fashion & Apparel',
        'Automotive Parts & Accessories',
      ],
      exemptions:
        'C2C private seller transactions are exempt from mandatory durability notices unless commercial seller status thresholds are triggered.',
      open_legal_questions: [
        {
          id: 'OLQ-001',
          question:
            'Does seller cross-border listing from UK to DE trigger mandatory Article 4(3) repairability disclosures?',
          asked_by: {
            id: 'USR-002',
            name: 'Marcus Vance',
            email: 'marcus.vance@ebay.com',
            role: 'Lead PM',
          },
          date_raised: '2026-01-20',
          resolution:
            'Yes, destination-based enforcement applies if shipping to EU consumer destination.',
          status: 'Resolved',
          linked_obligation_id: 'OBL-LRD-2024-001-004',
        },
        {
          id: 'OLQ-002',
          question:
            'What third-party verification standard is accepted for private brand eco-labels under Article 3(1)(a)?',
          asked_by: {
            id: 'USR-001',
            name: 'Elena Rostova',
            email: 'elena.rostova@ebay.com',
            role: 'Legal Counsel',
          },
          date_raised: '2026-02-01',
          resolution: undefined,
          status: 'Open',
          linked_obligation_id: 'OBL-LRD-2024-001-001',
        },
        {
          id: 'OLQ-003',
          question:
            'Are refurbished computing devices subject to Article 6(1) software update disclosure mandates?',
          asked_by: {
            id: 'USR-003',
            name: 'Sarah Chen',
            email: 'sarah.chen@ebay.com',
            role: 'Senior PM',
          },
          date_raised: '2026-02-15',
          resolution: undefined,
          status: 'Escalated',
          linked_obligation_id: 'OBL-LRD-2024-001-005',
        },
      ],
      related_lrds: [],
    },
    approvals: [
      {
        approver: {
          id: 'USR-001',
          name: 'Elena Rostova',
          email: 'elena.rostova@ebay.com',
          role: 'Senior Legal Counsel',
        },
        role: 'Senior Legal Counsel',
        date: '2026-02-10T14:30:00Z',
        confirmed_via: 'email',
      },
    ],
  },
  'art-lrd-101': {
    id: 'art-lrd-101',
    urn: 'urn:regulus:lrd:LRD-AI-ACT-ART14',
    title: 'EU AI Act Article 14 Oversight Requirement',
    regulation: 'EU Regulation 2024/1689 (EU AI Act)',
    jurisdiction: ['EU', 'DE', 'FR', 'ES', 'IT'],
    enforcement_date: '2026-08-02',
    grace_period_end: '2027-02-02',
    lrd_owner: {
      id: 'USR-001',
      name: 'Elena Rostova',
      email: 'elena.rostova@ebay.com',
      role: 'Legal Counsel',
    },
    pm_owner: {
      id: 'USR-003',
      name: 'Sarah Chen',
      email: 'sarah.chen@ebay.com',
      role: 'PM',
    },
    status: 'Approved',
    version: '2.1.0',
    created: '2026-03-01T10:00:00Z',
    last_updated: '2026-07-20T16:00:00Z',
    sections: {
      legal_context:
        'Article 14 mandates human-in-the-loop (HITL) oversight mechanisms for high-risk AI systems to prevent or minimize risks to health, safety, or fundamental rights. Deployers must ensure natural persons assigned to oversight have necessary competence and authority.',
      obligations: [
        {
          id: 'OBL-AIACT-001',
          urn: 'urn:regulus:obligation:OBL-AIACT-001',
          article: 'Article 14(4)(a)',
          text: 'Enable human oversight individuals to fully understand system capacities and limitations to detect anomalies or unexpected output.',
          type: 'Process',
          affected_surface: ['Admin Dashboard', 'Model Telemetry Queue'],
          notes: 'Requires real-time alert triggers when confidence thresholds drop below 85%.',
          traceability_refs: ['brd-201', 'prd-301'],
        },
        {
          id: 'OBL-AIACT-002',
          urn: 'urn:regulus:obligation:OBL-AIACT-002',
          article: 'Article 14(4)(d)',
          text: 'Provide direct mechanism to interrupt automated operation through a stop button or human override switch.',
          type: 'Process',
          affected_surface: ['Action Center', 'API Gateway'],
          notes: 'Must log reason for intervention to compliance audit database.',
          traceability_refs: ['sub-401', 'jira-501'],
        },
      ],
      ebay_applicability:
        'Applies to all automated buyer/seller recommendation engines, generative listing copy generators, and risk scoring models deployed across EU sites.',
      affected_categories: ['Generative AI Services', 'Risk Scoring', 'Seller Verification'],
      exemptions: 'Internal sandbox models and non-deployable R&D prototypes.',
      open_legal_questions: [
        {
          id: 'OLQ-AIACT-01',
          question:
            'What SLA is required for human intervention when real-time content policy violation is flagged?',
          asked_by: {
            id: 'USR-003',
            name: 'Sarah Chen',
            email: 'sarah.chen@ebay.com',
            role: 'PM',
          },
          date_raised: '2026-06-10',
          resolution: 'SLA threshold set to 15 minutes for high-risk flags.',
          status: 'Resolved',
          linked_obligation_id: 'OBL-AIACT-002',
        },
      ],
      related_lrds: ['LRD-2024-001'],
    },
    approvals: [
      {
        approver: {
          id: 'USR-001',
          name: 'Elena Rostova',
          email: 'elena.rostova@ebay.com',
          role: 'Legal Counsel',
        },
        role: 'Legal Counsel',
        date: '2026-07-20T16:00:00Z',
        confirmed_via: 'email',
      },
    ],
    audit_log: [
      {
        id: 'LOG-101',
        timestamp: '2026-07-20T16:00:00Z',
        author: {
          name: 'Elena Rostova',
          role: 'Legal Counsel',
          email: 'elena.rostova@ebay.com',
        },
        targetComponent: 'Approval',
        action: 'Signed Off',
        summary: 'Recorded formal Legal Counsel sign-off for LRD ratification.',
      },
      {
        id: 'LOG-102',
        timestamp: '2026-07-15T11:30:00Z',
        author: {
          name: 'Sarah Chen',
          role: 'PM',
          email: 'sarah.chen@ebay.com',
        },
        targetComponent: 'Open Question',
        action: 'Resolved',
        summary: 'Resolved Open Question OLQ-AIACT-01 regarding SLA threshold for human intervention.',
        changes: [
          {
            field: 'status',
            oldValue: 'Open',
            newValue: 'Resolved',
          },
          {
            field: 'resolution',
            oldValue: 'None',
            newValue: 'SLA threshold set to 15 minutes for high-risk flags.',
          },
        ],
      },
      {
        id: 'LOG-103',
        timestamp: '2026-03-01T10:00:00Z',
        author: {
          name: 'Elena Rostova',
          role: 'Legal Counsel',
          email: 'elena.rostova@ebay.com',
        },
        targetComponent: 'Overview Context',
        action: 'Created',
        summary: 'Created initial LRD draft for EU AI Act Article 14 Oversight Requirement.',
      },
    ],
  },
};

export const INITIAL_PROJECTS: Project[] = [
  {
    id: 'prj-ecgt',
    name: 'ECGT - Enterprise Generative AI Governance & Traceability',
    code: 'ECGT-2025',
    regulation: 'EU AI Act',
    program: 'ECGT',
    pm: 'Sarah Chen',
    phase: 'Execution',
    status: 'At Risk',
    brdStatus: 'Approved',
    prdStatus: 'In Review',
    complianceDate: '2026-08-28',
    daysToEnforcement: 25, // red <= 30
    complianceScore: 78,
    description: 'Framework for high-risk generative AI model lineage, auditability, human oversight, and automated risk thresholds under EU AI Act Article 14.',
    airtableSyncStatus: 'In Sync',
    lastSyncedAt: '2026-08-03 18:45',
    rasci: {
      responsible: 'Sarah Chen (PM)',
      accountable: 'Elena Rostova (Legal Manager)',
      supportedBy: 'David Kim (Eng Lead)',
      consulted: 'Marcus Vance (BU Lead)',
      informed: 'All Regulus Committee Members',
    },
  },
  {
    id: 'prj-dora',
    name: 'DORA Digital Operational Resilience Framework',
    code: 'DORA-ICT',
    regulation: 'DORA',
    program: 'Cross-Border Data',
    pm: 'Marcus Vance',
    phase: 'Verification',
    status: 'On Track',
    brdStatus: 'Approved',
    prdStatus: 'Approved',
    complianceDate: '2026-10-15',
    daysToEnforcement: 73, // yellow <= 90
    complianceScore: 92,
    description: 'ICT third-party risk management, major incident reporting protocols, and digital operational resilience testing across payment gateways.',
    airtableSyncStatus: 'Pending Sync',
    lastSyncedAt: '2026-08-02 12:10',
    rasci: {
      responsible: 'Marcus Vance (PM)',
      accountable: 'Marcus Vance (PM)',
      supportedBy: 'Alex Rivera (Security Lead)',
      consulted: 'Elena Rostova (Legal Counsel)',
      informed: 'Risk & IT SteerCo',
    },
  },
  {
    id: 'prj-esg',
    name: 'CSRD Corporate Sustainability Reporting 2025',
    code: 'ESG-CSRD',
    regulation: 'ESG Disclosures',
    program: 'Wealth & Markets',
    pm: 'Elena Rostova',
    phase: 'Framing',
    status: 'Blocked',
    brdStatus: 'In Review',
    prdStatus: 'Draft',
    complianceDate: '2026-12-31',
    daysToEnforcement: 150, // green > 90
    complianceScore: 61,
    description: 'Automated double-materiality assessment pipeline and Scope 1-3 carbon metrics tracking for institutional portfolio reporting.',
    airtableSyncStatus: 'Conflict',
    lastSyncedAt: '2026-08-01 09:30',
    rasci: {
      responsible: 'Elena Rostova (PM)',
      accountable: 'Elena Rostova (Legal Counsel)',
      supportedBy: 'Sarah Chen (PM)',
      consulted: 'Sustainability Board',
      informed: 'Executive Committee',
    },
  },
  {
    id: 'prj-mica',
    name: 'MiCA Stablecoin & Asset-Referenced Tokens',
    code: 'MICA-ART',
    regulation: 'MiCA',
    program: 'Wealth & Markets',
    pm: 'David Kim',
    phase: 'Discovery',
    status: 'On Track',
    brdStatus: 'Draft',
    prdStatus: 'Draft',
    complianceDate: '2027-03-31',
    daysToEnforcement: 240, // green > 90
    complianceScore: 45,
    description: 'Reserve asset auditing, whitepaper disclosures, and liquidity buffer controls for CASP licensing in the European Economic Area.',
    airtableSyncStatus: 'In Sync',
    lastSyncedAt: '2026-08-03 20:00',
    rasci: {
      responsible: 'David Kim (PM)',
      accountable: 'David Kim (PM)',
      supportedBy: 'Legal Compliance Desk',
      consulted: 'Treasury Desk',
      informed: 'Group Risk',
    },
  },
  {
    id: 'prj-gdpr',
    name: 'GDPR Cross-Border Data Lineage & Consent 2.0',
    code: 'GDPR-CL2',
    regulation: 'GDPR',
    program: 'Cross-Border Data',
    pm: 'Sarah Chen',
    phase: 'Sign-off',
    status: 'Completed',
    brdStatus: 'Approved',
    prdStatus: 'Approved',
    complianceDate: '2026-09-01',
    daysToEnforcement: 29, // red <= 30
    complianceScore: 98,
    description: 'Standard Contractual Clauses (SCC) automated validation and consent revocation engine across multi-region cloud databases.',
    airtableSyncStatus: 'In Sync',
    lastSyncedAt: '2026-08-03 14:20',
    rasci: {
      responsible: 'Sarah Chen (PM)',
      accountable: 'Sarah Chen (PM)',
      supportedBy: 'Data Protection Officer',
      consulted: 'Cloud Ops Team',
      informed: 'All Employees',
    },
  },
];

export const INITIAL_ARTIFACTS: Record<string, ArtifactNode[]> = {
  'prj-ecgt': [
    {
      id: 'art-lrd-101',
      title: 'EU AI Act Article 14 Oversight Requirement',
      tier: 'LRD',
      status: 'Approved',
      version: 'v2.1',
      complianceScore: 100,
      lastUpdated: '2026-07-20',
      owner: 'Elena Rostova (Legal Counsel)',
      link: '#',
      summary: 'Mandates human-in-the-loop intervention mechanisms for high-risk biometric & generative AI systems deployed in financial services.',
      projectId: 'prj-ecgt',
    },
    {
      id: 'art-brd-201',
      title: 'BRD-ECGT-01 Model Monitoring & Audit Trails',
      tier: 'BRD',
      status: 'Approved',
      version: 'v1.4',
      complianceScore: 92,
      lastUpdated: '2026-07-28',
      owner: 'Sarah Chen (PM)',
      link: '#',
      summary: 'Specifies real-time hallucination detection logs, human override kill switches, and automated compliance snapshot archiving.',
      projectId: 'prj-ecgt',
    },
    {
      id: 'art-prd-301',
      title: 'E2E PRD - ECGT Engine Architecture',
      tier: 'PRD',
      status: 'In Review',
      version: 'v1.0-rc2',
      complianceScore: 84,
      lastUpdated: '2026-08-01',
      owner: 'Sarah Chen (PM)',
      link: '#',
      summary: 'Technical architecture for prompt interceptors, telemetry storage in Cloud Firestore, and Neo4j lineage sync.',
      projectId: 'prj-ecgt',
    },
    {
      id: 'art-sub-401',
      title: 'Sub-PRD Telemetry & Cascade Engine',
      tier: 'Sub-PRD',
      status: 'Draft',
      version: 'v0.9',
      complianceScore: 70,
      lastUpdated: '2026-08-02',
      owner: 'David Kim (Eng Lead)',
      link: '#',
      summary: 'Detailed API schemas and event queues for propagating downstream requirement changes upon LRD modification.',
      projectId: 'prj-ecgt',
    },
    {
      id: 'art-jira-501',
      title: 'REG-1042 Implement Human Override Endpoint',
      tier: 'Jira',
      status: 'Implemented',
      version: 'v1.0',
      complianceScore: 95,
      lastUpdated: '2026-08-03',
      owner: 'David Kim (Eng Lead)',
      link: 'https://jira.regulus.internal/browse/REG-1042',
      summary: 'REST endpoint `/api/v1/override` for human sign-off on flagged model responses.',
      projectId: 'prj-ecgt',
    },
  ],
  'prj-dora': [
    {
      id: 'art-lrd-102',
      title: 'DORA Regulation (EU) 2022/2554 Article 28',
      tier: 'LRD',
      status: 'Approved',
      version: 'v1.0',
      complianceScore: 100,
      lastUpdated: '2026-06-15',
      owner: 'Elena Rostova (Legal Counsel)',
      link: '#',
      summary: 'General principles for financial entities managing third-party ICT risk and vendor concentration.',
      projectId: 'prj-dora',
    },
    {
      id: 'art-brd-202',
      title: 'BRD-DORA Vendor Risk Assessment Portal',
      tier: 'BRD',
      status: 'Approved',
      version: 'v2.0',
      complianceScore: 94,
      lastUpdated: '2026-07-10',
      owner: 'Marcus Vance (PM)',
      link: '#',
      summary: 'Quarterly continuous vendor telemetry and SLA breach auto-escalation triggers.',
      projectId: 'prj-dora',
    },
    {
      id: 'art-prd-302',
      title: 'PRD - Incident Response & Escalation Engine',
      tier: 'PRD',
      status: 'Approved',
      version: 'v1.2',
      complianceScore: 90,
      lastUpdated: '2026-07-25',
      owner: 'Marcus Vance (PM)',
      link: '#',
      summary: 'Integration with PagerDuty and regulatory notification templates for 4-hour major incident reporting.',
      projectId: 'prj-dora',
    },
  ],
};

export const INITIAL_RISKS: Record<string, RiskItem[]> = {
  'prj-ecgt': [
    {
      id: 'r-1',
      projectId: 'prj-ecgt',
      riskTitle: 'Latency spike in real-time prompt compliance evaluation',
      category: 'Technical',
      severity: 'High',
      likelihood: 'Medium',
      score: 16,
      status: 'Open',
      mitigation: 'Implement async batch verification with speculative caching.',
      owner: 'David Kim',
    },
    {
      id: 'r-2',
      projectId: 'prj-ecgt',
      riskTitle: 'Ambiguity in EU AI Act Article 14 audit log retention specs',
      category: 'Legal',
      severity: 'High',
      likelihood: 'High',
      score: 20,
      status: 'Under Review',
      mitigation: 'Escalated to Legal Committee for formal interpretation note.',
      owner: 'Elena Rostova',
    },
    {
      id: 'r-3',
      projectId: 'prj-ecgt',
      riskTitle: 'Missing fallback mechanisms if downstream model vendor fails',
      category: 'Operational',
      severity: 'Medium',
      likelihood: 'Low',
      score: 8,
      status: 'Mitigated',
      mitigation: 'Secondary local LLM deployment configured for offline fallback.',
      owner: 'Sarah Chen',
    },
  ],
};

export const INITIAL_DECISIONS: DecisionItem[] = [
  {
    id: 'dec-101',
    projectId: 'prj-ecgt',
    projectName: 'ECGT - Enterprise Generative AI Governance & Traceability',
    regulation: 'EU AI Act',
    title: 'Adoption of Neo4j Graph DB for Traceability Topology',
    type: 'Architectural',
    decisionMaker: 'David Kim (Eng Lead)',
    status: 'Signed Off',
    date: '2026-07-14',
    forum: 'Architecture Board',
    rationale: 'Neo4j Cypher enables sub-second 5-hop directional lineage graph queries compared to recursive SQL.',
  },
  {
    id: 'dec-102',
    projectId: 'prj-ecgt',
    projectName: 'ECGT - Enterprise Generative AI Governance & Traceability',
    regulation: 'EU AI Act',
    title: 'Human Oversight Intervention Threshold set to 0.85 Confidence',
    type: 'Regulatory Interpretation',
    decisionMaker: 'Elena Rostova (Legal Counsel)',
    status: 'Under Review',
    date: '2026-07-29',
    forum: 'Legal Committee',
    rationale: 'Any model output with confidence below 85% must hit the Action Center HITL queue before release to user.',
  },
  {
    id: 'dec-103',
    projectId: 'prj-dora',
    projectName: 'DORA Digital Operational Resilience Framework',
    regulation: 'DORA',
    title: 'Mandatory Multi-Cloud Redundancy for Critical Payment Services',
    type: 'Policy Approval',
    decisionMaker: 'Marcus Vance (PM)',
    status: 'Signed Off',
    date: '2026-06-30',
    forum: 'SteerCo',
    rationale: 'Ensures zero single point of failure across cloud providers as mandated by Article 28.',
  },
  {
    id: 'dec-104',
    projectId: 'prj-esg',
    projectName: 'CSRD Corporate Sustainability Reporting 2025',
    regulation: 'ESG Disclosures',
    title: 'Exclusion of Unverified Scope 3 Upstream Estimates in Q3 Pack',
    type: 'Scope Adjustment',
    decisionMaker: 'Elena Rostova (PM)',
    status: 'Proposed',
    date: '2026-08-01',
    forum: 'PMO',
    rationale: 'Avoid regulatory penalty for inaccurate greenwashing assertions until audit verification completes.',
  },
];

export const INITIAL_MILESTONES: Record<string, MilestoneItem[]> = {
  'prj-ecgt': [
    {
      id: 'm-1',
      projectId: 'prj-ecgt',
      workstream: 'Legal Baseline',
      title: 'LRD Sign-off & Article 14 Rule Set Mapping',
      poc: 'Elena Rostova',
      targetDate: '2026-07-15',
      status: 'Completed',
    },
    {
      id: 'm-2',
      projectId: 'prj-ecgt',
      workstream: 'Core Architecture',
      title: 'Firestore Schema & Neo4j Lineage Sync Pipeline',
      poc: 'David Kim',
      targetDate: '2026-08-10',
      status: 'In Progress',
    },
    {
      id: 'm-3',
      projectId: 'prj-ecgt',
      workstream: 'HITL Action Center',
      title: 'Cascade Proposal & Approval Gate Integration',
      poc: 'Sarah Chen',
      targetDate: '2026-08-20',
      status: 'In Progress',
    },
    {
      id: 'm-4',
      projectId: 'prj-ecgt',
      workstream: 'Verification',
      title: 'End-to-End Compliance Simulation & Red Teaming',
      poc: 'Alex Rivera',
      targetDate: '2026-08-26',
      status: 'Not Started',
    },
  ],
};

export const INITIAL_TASKS: Record<string, TaskItem[]> = {
  'prj-ecgt': [
    {
      id: 't-1',
      projectId: 'prj-ecgt',
      title: 'Draft LRD for Article 14 Sub-clause 3',
      workstream: 'Legal Baseline',
      assignee: 'Elena Rostova',
      priority: 'High',
      status: 'Done',
      dueDate: '2026-07-20',
    },
    {
      id: 't-2',
      projectId: 'prj-ecgt',
      title: 'Implement Next.js Action Center HITL Hub',
      workstream: 'HITL Action Center',
      assignee: 'Sarah Chen',
      priority: 'High',
      status: 'In Progress',
      dueDate: '2026-08-08',
    },
    {
      id: 't-3',
      projectId: 'prj-ecgt',
      title: 'Configure Playwright End-to-End Suite',
      workstream: 'QA & Testing',
      assignee: 'David Kim',
      priority: 'Medium',
      status: 'Todo',
      dueDate: '2026-08-12',
    },
    {
      id: 't-4',
      projectId: 'prj-ecgt',
      title: 'Airtable Bi-Directional Field Mapping Validation',
      workstream: 'Integrations',
      assignee: 'Marcus Vance',
      priority: 'High',
      status: 'Blocked',
      dueDate: '2026-08-15',
    },
    {
      id: 't-5',
      projectId: 'prj-ecgt',
      title: 'Benchmark Cypher Graph Query Latency',
      workstream: 'Core Architecture',
      assignee: 'David Kim',
      priority: 'Low',
      status: 'Backlog',
      dueDate: '2026-08-22',
    },
  ],
};

export const INITIAL_VERSION_HISTORY: Record<string, VersionHistoryItem[]> = {
  'prj-ecgt': [
    {
      id: 'ver-101',
      projectId: 'prj-ecgt',
      artifactName: 'EU AI Act Article 14 Oversight Requirement (LRD)',
      version: 'v2.1',
      author: 'Elena Rostova',
      timestamp: '2026-07-20 14:30',
      summary: 'Added explicit requirement for human override capability before output release.',
      diffBefore: 'Section 4.1: Model outputs must be logged to audit store within 24 hours.',
      diffAfter: 'Section 4.1: Model outputs with confidence score < 0.85 must be routed to Action Center HITL queue for real-time human approval prior to user display.',
    },
    {
      id: 'ver-102',
      projectId: 'prj-ecgt',
      artifactName: 'BRD-ECGT-01 Model Monitoring & Audit Trails',
      version: 'v1.4',
      author: 'Sarah Chen',
      timestamp: '2026-07-28 11:15',
      summary: 'Updated latency SLA from 500ms to 200ms for prompt validation engine.',
      diffBefore: 'Performance SLA: Maximum latency budget for compliance interceptor is 500ms.',
      diffAfter: 'Performance SLA: Maximum latency budget for compliance interceptor is 200ms using speculative caching.',
    },
  ],
};

export const INITIAL_ACTION_CENTER: ActionCenterItem[] = [
  {
    id: 'act-1',
    title: 'Cascade Proposal #402 - LRD Article 14 Amendment',
    type: 'Cascade Proposal',
    sourceAgent: 'Cascade Proposal Agent',
    priority: 'Urgent',
    projectId: 'prj-ecgt',
    projectName: 'ECGT - Enterprise Generative AI Governance & Traceability',
    contextSummary: 'Modification in LRD-101 requires cascading updates to BRD-201 and PRD-301 compliance specifications.',
    deadline: '2026-08-05 17:00',
    status: 'Pending',
    slackNotified: true,
    artifactAffected: 'BRD-ECGT-01 & PRD-301',
    diffSnippet: {
      before: 'SLA: 500ms logging without blocking.',
      after: 'SLA: 200ms blocking evaluation with human override gate.',
    },
  },
  {
    id: 'act-2',
    title: 'HITL Gate: High-Risk Prompt Model Override',
    type: 'HITL approval gate',
    sourceAgent: 'System Engine',
    priority: 'High',
    projectId: 'prj-ecgt',
    projectName: 'ECGT - Enterprise Generative AI Governance & Traceability',
    contextSummary: 'Generative AI query triggered risk threshold (Confidence score 0.76 < 0.85). Human review required.',
    deadline: '2026-08-04 12:00',
    status: 'Pending',
    slackNotified: false,
    artifactAffected: 'REG-1042 Endpoint Engine',
  },
  {
    id: 'act-3',
    title: 'Decision Sign-Off: Human Oversight Intervention Threshold',
    type: 'Decision sign-off',
    sourceAgent: 'Legal Compliance Agent',
    priority: 'High',
    projectId: 'prj-ecgt',
    projectName: 'ECGT - Enterprise Generative AI Governance & Traceability',
    contextSummary: 'Formal approval request for 0.85 confidence threshold decision signed by Legal Counsel.',
    deadline: '2026-08-06 18:00',
    status: 'Pending',
    slackNotified: true,
  },
  {
    id: 'act-4',
    title: 'Meeting Extraction: SteerCo Alignment Items',
    type: 'Meeting extraction',
    sourceAgent: 'Meeting Transcript Agent',
    priority: 'Medium',
    projectId: 'prj-dora',
    projectName: 'DORA Digital Operational Resilience Framework',
    contextSummary: 'Extracted 3 action items from 08/02 SteerCo recording regarding vendor SLA penalties.',
    deadline: '2026-08-07 10:00',
    status: 'Pending',
    slackNotified: false,
  },
  {
    id: 'act-5',
    title: 'Airtable Sync Conflict: Project Phase Mismatch',
    type: 'Airtable sync conflict',
    sourceAgent: 'Airtable Sync Agent',
    priority: 'Medium',
    projectId: 'prj-esg',
    projectName: 'CSRD Corporate Sustainability Reporting 2025',
    contextSummary: 'Regulus phase is "Framing" while Airtable base `appsAttrVGoHjSfHR` displays "Execution".',
    deadline: '2026-08-05 09:00',
    status: 'Pending',
    slackNotified: false,
  },
  {
    id: 'act-6',
    title: 'Agent Draft Review: LRD for DORA Article 28 Clause 4',
    type: 'Agent draft review',
    sourceAgent: 'LRD Synthesis Agent',
    priority: 'Low',
    projectId: 'prj-dora',
    projectName: 'DORA Digital Operational Resilience Framework',
    contextSummary: 'Automated legal draft generated for vendor audit rights. Requires legal counsel review before locking.',
    deadline: '2026-08-10 15:00',
    status: 'Pending',
    slackNotified: true,
  },
];

export const GRAPH_NODES: ArtifactNode[] = [
  {
    id: 'lrd-101',
    title: 'LRD: EU AI Act Art. 14',
    tier: 'LRD',
    status: 'Approved',
    version: 'v2.1',
    complianceScore: 100,
    lastUpdated: '2026-07-20',
    owner: 'Elena Rostova',
    link: '#',
    summary: 'Legal baseline requiring human oversight in high-risk AI.',
    projectId: 'prj-ecgt',
  },
  {
    id: 'brd-201',
    title: 'BRD: ECGT Audit Trails',
    tier: 'BRD',
    status: 'Approved',
    version: 'v1.4',
    complianceScore: 92,
    lastUpdated: '2026-07-28',
    owner: 'Sarah Chen',
    link: '#',
    summary: 'Business requirement for real-time model monitoring.',
    projectId: 'prj-ecgt',
  },
  {
    id: 'prd-301',
    title: 'PRD: ECGT Engine Arch',
    tier: 'PRD',
    status: 'In Review',
    version: 'v1.0',
    complianceScore: 84,
    lastUpdated: '2026-08-01',
    owner: 'Sarah Chen',
    link: '#',
    summary: 'Technical architecture for prompt interceptors.',
    projectId: 'prj-ecgt',
  },
  {
    id: 'sub-401',
    title: 'Sub-PRD: Cascade Engine',
    tier: 'Sub-PRD',
    status: 'Draft',
    version: 'v0.9',
    complianceScore: 70,
    lastUpdated: '2026-08-02',
    owner: 'David Kim',
    link: '#',
    summary: 'Event queue for downstream rule propagation.',
    projectId: 'prj-ecgt',
  },
  {
    id: 'jira-501',
    title: 'Jira: REG-1042 Endpoint',
    tier: 'Jira',
    status: 'Implemented',
    version: 'v1.0',
    complianceScore: 95,
    lastUpdated: '2026-08-03',
    owner: 'David Kim',
    link: '#',
    summary: 'Override REST endpoint.',
    projectId: 'prj-ecgt',
  },
  {
    id: 'lrd-102',
    title: 'LRD: DORA Art. 28',
    tier: 'LRD',
    status: 'Approved',
    version: 'v1.0',
    complianceScore: 100,
    lastUpdated: '2026-06-15',
    owner: 'Elena Rostova',
    link: '#',
    summary: 'ICT third-party risk principles.',
    projectId: 'prj-dora',
  },
  {
    id: 'brd-202',
    title: 'BRD: DORA Vendor Portal',
    tier: 'BRD',
    status: 'Approved',
    version: 'v2.0',
    complianceScore: 94,
    lastUpdated: '2026-07-10',
    owner: 'Marcus Vance',
    link: '#',
    summary: 'Vendor risk telemetry requirements.',
    projectId: 'prj-dora',
  },
];

export const GRAPH_EDGES: ArtifactEdge[] = [
  { id: 'e1', source: 'lrd-101', target: 'brd-201', label: 'MANDATES' },
  { id: 'e2', source: 'brd-201', target: 'prd-301', label: 'DERIVES_FROM' },
  { id: 'e3', source: 'prd-301', target: 'sub-401', label: 'MAPS_TO' },
  { id: 'e4', source: 'sub-401', target: 'jira-501', label: 'IMPLEMENTS' },
  { id: 'e5', source: 'jira-501', target: 'lrd-101', label: 'DELIVERS' },
  { id: 'e6', source: 'lrd-102', target: 'brd-202', label: 'MANDATES' },
];
